Allow special version names that don't match Cargo.toml
This permits names that start with `TEST-` or end with
`-DO-NOT-USE`, printing a different "OK" message for them.

The check comes after the comparison to the version in
`Cargo.toml`, which is still always looked up, for three reasons:

- Although it would be very weird and probably a bad idea to put a
  `-DO-NOT-USE` version in `Cargo.toml`, if it were ever done
  accidentally or on purpose, the message indicating a match to
  `Cargo.toml` should still be written.

- Having code paths that are only exercised for actual releases and
  rarely or never in testing is likely to lead to bugs.

- For looking it up and reporting it initially: this information is
  potentially valuable even when deliberately not used.

This commit also makes two other changes in that same script step:

- A custom message is now printed if the version is rejected only
  because it didn't have the "v" prefix (which this project's
  version tags and GitHub release names are using).

- Stylistic adjustment, mostly to match the quoting style used
  throughout the workflow.

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -40,15 +40,22 @@ jobs:
       - name: Validate version against Cargo.toml
         run: |
           manifest_version="$(yq -r .package.version Cargo.toml)"
-          echo "version to give the release: $VERSION"
+          echo "version to name the release: $VERSION"
           echo "version Cargo.toml suggests: v$manifest_version"
 
           case "$VERSION" in
-          "v$manifest_version")
-            echo "OK: Version to give the relase agrees with top-level Cargo.toml."
+          "v$manifest_version" )
+            echo 'OK: Version to name the relase agrees with top-level Cargo.toml.'
             ;;
-          *)
-            echo "STOPPING: Version to give the release seems mistaken."
+          TEST-* | *-DO-NOT-USE )
+            echo 'OK: Version to name the release is strange but marked as such.'
+            ;;
+          "$manifest_version" )
+            echo 'STOPPING: Version to name the release is missing the leading "v".'
+            exit 1
+            ;;
+          * )
+            echo 'STOPPING: Version to name the release seems mistaken.'
             exit 1
             ;;
           esac
